const EDIT_EXAMPLES: string[] = [
  "Add a retro, vintage filter",
  "Make the sky a vibrant sunset",
  "Change my hair to electric blue",
  "Remove the person in the background",
  "Turn the photo into a watercolor painting",
  "Apply a cool, cinematic blue tone",
  "Add a warm, golden hour glow",
  "Make it black and white, but keep the red car",
  "Increase the contrast for a dramatic look",
  "Add a mysterious fog or mist",
  "Place a curious cat on the windowsill",
  "Change the background to a bustling Tokyo street",
  "Apply a neon-noir art style",
  "Make the image look like a comic book panel",
  "Add falling snow to the scene",
  "Surround the subject with floating glowing particles",
  "Change the season to autumn with falling leaves",
  "Give the subject futuristic cybernetic implants",
  "Replace the coffee mug with a medieval potion bottle",
  "Add a lens flare effect coming from the sun",
  "Make the shadows longer and more dramatic",
  "Desaturate the image for a moody feel",
  "Apply a mosaic tile effect",
  "Create a double exposure with a forest silhouette",
  "Add a dragon flying in the sky",
  "Change the clothing to a spacesuit",
  "Make the plants overgrown and jungle-like",
  "Add rain and reflections on the ground",
  "Turn the day into night with a starry sky",
  "Give the image a soft, dreamy focus",
  "Apply a fisheye lens effect",
  "Sharpen the details to make them pop",
  "Add a subtle vignette to the corners",
  "Change the eye color to bright green",
  "Make it look like an old, cracked photograph",
  "Add a holographic interface in front of the person",
  "Place them in the middle of a desert",
  "Transform the car into a retro convertible",
  "Add a ghostly apparition in the background",
  "Make the lighting look like it's underwater",
  "Apply a pop art style like Andy Warhol",
  "Add steampunk goggles and gears",
  "Change the texture of the wall to exposed brick",
  "Make the image look like it's printed on canvas",
  "Add a flock of birds flying across the sky",
  "Give the photo a grainy, film-like texture",
  "Surround the subject with a magical aura",
  "Change the floor to a reflective, mirror-like surface",
  "Add butterfly wings to the person",
  "Make the entire scene look like a miniature model",
  "Apply a glitch art effect",
  "Add a rainbow arching across the sky",
  "Place a full moon in the background",
  "Make the colors psychedelic and swirling",
  "Change the background to a serene Japanese garden",
  "Add a sword strapped to their back",
  "Give the image a painted, impasto style",
  "Make the room look abandoned and dusty",
  "Add floating lanterns in the air",
  "Transform the background into a library of ancient books",
  "Add a glowing tattoo to their arm",
  "Make the subject appear as a constellation of stars",
  "Change the setting to a beautiful coral reef",
  "Add a crown of flowers to their hair",
  "Apply a cross-stitch pattern to the image",
  "Make the building look like a gothic cathedral",
  "Add a small robot companion next to them",
  "Give the scene an eerie, haunted atmosphere",
  "Change the background to the inside of a spaceship",
  "Add fireflies lighting up the evening",
  "Make the image appear as a reflection in a puddle",
  "Apply an anaglyph 3D effect (red/cyan)",
  "Surround them with musical notes",
  "Change the car into a horse-drawn carriage",
  "Add a majestic waterfall in the background",
  "Make the ground look like a chessboard",
  "Give the subject elven ears",
  "Add a galaxy swirling within the coffee cup",
  "Turn the background into a field of sunflowers",
  "Add a vintage microphone on a stand",
  "Apply a blueprint-style architectural drawing effect",
  "Make the trees look like they are made of crystal",
  "Add a pirate ship on the horizon",
  "Change the lighting to be from a single candle",
  "Surround the scene with a baroque, ornate frame",
  "Add a phoenix rising from flames",
  "Make the clouds look like they are made of cotton candy",
  "Put them on the cover of a sci-fi novel",
  "Change the texture to look like worn leather",
  "Add a hidden message written on the wall",
  "Make the subject's shadow a different creature",
  "Apply a stained glass window effect",
  "Add a winding cobblestone path",
  "Change the background to a vast mountain range",
  "Give them a superhero cape that is billowing in the wind",
  "Make the scene look like it's from a Wes Anderson film",
  "Add a classic film projector light beam",
  "Transform the landscape into a low-poly art style",
  "Place a vintage record player in the room",
  "Add a mysterious, glowing doorway in the background"
];

export default EDIT_EXAMPLES;
