const EDIT_EXAMPLES: string[] = [
  "Apply a 1970s faded film look with high grain",
  "Transform the sky into a dramatic sunset with deep orange and purple clouds",
  "Change my hair color to a vibrant, electric blue",
  "Carefully remove the tourists walking in the background",
  "Convert the entire image into a detailed watercolor painting",
  "Apply a cool, cinematic blue color grade, like a sci-fi movie",
  "Add a warm, golden hour glow over the entire scene",
  "Make it black and white, but keep the red rose in full color",
  "Dramatically increase the contrast and deepen the shadows",
  "Introduce a layer of mysterious, thick fog rolling in from the ground",
  "Place a curious black cat sitting on the stone wall",
  "Change the background to a bustling, neon-lit Tokyo street at night",
  "Redraw the image in a neon-noir art style with glowing highlights",
  "Re-render the scene to look like a panel from a vintage comic book",
  "Add photorealistic falling snow and accumulation on surfaces",
  "Surround the subject with floating, glowing magical particles",
  "Change the season to a crisp autumn day with vibrant falling leaves",
  "Give the subject subtle, futuristic cybernetic facial implants",
  "Replace the modern coffee mug with an ornate, medieval potion bottle",
  "Add a cinematic lens flare effect originating from the top-left corner",
  "Make the shadows long and dramatic as if it's late afternoon",
  "Desaturate all colors except for a single object for emphasis",
  "Apply a vibrant mosaic tile effect across the entire image",
  "Create a double exposure effect with a silhouette of a dense forest",
  "Add a majestic, fire-breathing dragon flying high in the sky",
  "Change the modern clothing into a detailed, well-fitted astronaut suit",
  "Make the background plants overgrown and jungle-like, with vines wrapping around the pillars",
  "Add heavy rain with realistic reflections on the wet ground",
  "Turn the daytime scene into a clear night with a starry sky and a full moon",
  "Give the image a soft, dreamy focus with a gentle blur",
  "Apply a distorted fisheye lens effect to the entire photo",
  "Sharpen the fine details in the architecture to make them pop",
  "Add a subtle, dark vignette to the corners to frame the subject",
  "Change the subject's eye color to a striking, bright green",
  "Make the photo look like an old, cracked, and faded photograph from the 1800s",
  "Overlay a holographic user interface in front of the person",
  "Place the subject in the middle of a vast, sandy desert at noon",
  "Transform the modern car into a classic 1950s retro convertible",
  "Add a semi-transparent, ghostly apparition in the background window",
  "Change the lighting to make it look like the scene is underwater",
  "Apply a pop art style with bold colors and dots, like Andy Warhol",
  "Add steampunk elements like brass goggles and intricate gears",
  "Change the texture of the plaster wall to weathered, exposed brick",
  "Make the image look like it's an oil painting on a textured canvas",
  "Add a flock of birds silhouetted against the sky",
  "Give the photo a grainy, high-ISO, 35mm film-like texture",
  "Surround the subject with a swirling, magical blue aura",
  "Change the wooden floor to a highly reflective, polished marble surface",
  "Add intricate, gossamer butterfly wings to the person's back",
  "Make the entire scene look like a tilt-shift, miniature model",
  "Apply a digital glitch art effect with datamoshing and RGB shifts",
  "Add a vibrant, double rainbow arching across the entire sky",
  "Place a huge, detailed full moon in the background sky",
  "Make the colors psychedelic, swirling, and intensely saturated",
  "Change the background to a serene, traditional Japanese garden with a koi pond",
  "Add a detailed, ornate sword strapped to their back",
  "Give the image a painted style with thick, visible brushstrokes (impasto)",
  "Make the room look abandoned, with dust particles in the air and cobwebs",
  "Add glowing, floating lanterns throughout the scene",
  "Transform the background into a vast library with ancient, leather-bound books",
  "Add a glowing, intricate tattoo sleeve to their left arm",
  "Make the subject appear as if they are made from a constellation of stars",
  "Change the setting to a beautiful, vibrant coral reef teeming with life",
  "Add a crown of daisies and wildflowers to their hair",
  "Apply a cross-stitch embroidery pattern to the entire image",
  "Make the modern building look like a towering gothic cathedral",
  "Add a small, friendly robot companion standing next to them",
  "Give the scene an eerie, haunted atmosphere with spooky lighting",
  "Change the background to the command bridge of a futuristic spaceship",
  "Add hundreds of glowing fireflies to the evening scene",
  "Make the image appear as a reflection in a rain puddle on a cobblestone street",
  "Apply an anaglyph 3D effect (requires red/cyan glasses)",
  "Surround them with floating, ethereal musical notes",
  "Change the car into an elegant, 19th-century horse-drawn carriage",
  "Add a majestic, powerful waterfall in the background",
  "Make the ground look like a perfectly tiled black and white chessboard",
  "Give the subject pointed, fantasy-style elven ears",
  "Add a swirling galaxy with nebulae inside the coffee cup",
  "Turn the background into a vast field of sunflowers reaching to the horizon",
  "Add a vintage 1940s-style microphone on a stand in front of them",
  "Apply a blueprint-style architectural drawing effect to the buildings",
  "Make the trees in the background look like they are made of shimmering crystal",
  "Add a menacing pirate ship with black sails on the horizon",
  "Change the lighting to look like it is coming from a single, flickering candle",
  "Surround the scene with a heavy, ornate, baroque-style frame",
  "Add a mythical phoenix with fiery wings rising from flames",
  "Make the clouds in the sky look like they are made of fluffy cotton candy",
  "Place the person on the cover of a vintage sci-fi novel",
  "Change the texture of their jacket to look like worn, cracked leather",
  "Add a mysterious, hidden message written in glowing runes on the wall",
  "Make the subject's shadow look like a completely different creature, like a wolf",
  "Apply a beautiful stained glass window effect to the entire scene",
  "Add a winding cobblestone path leading into the distance",
  "Change the background to a vast, snow-capped mountain range at sunrise",
  "Give them a superhero cape, long and red, that is billowing dramatically in the wind",
  "Make the scene's color palette and composition look like it's from a Wes Anderson film",
  "Add the light beam from a classic film projector cutting through the dark room",
  "Transform the entire landscape into a vibrant, low-poly art style",
  "Place a vintage record player with a spinning vinyl disc in the room",
  "Add a mysterious, glowing doorway standing in the middle of the field"
];

export default EDIT_EXAMPLES;
