const GENERATE_EXAMPLES: string[] = [
  "A photorealistic portrait of a wise old wizard with a long white beard",
  "A majestic lion wearing a crown, cinematic lighting",
  "A surreal underwater city with glowing jellyfish and bioluminescent coral",
  "A vintage travel poster for a vacation on Mars",
  "A friendly robot gardener tending to exotic alien plants, detailed illustration",
  "A cozy, cluttered artist's studio bathed in morning light",
  "An epic fantasy landscape with floating islands and waterfalls",
  "A cyberpunk city street at night, drenched in neon and rain",
  "A highly detailed macro photograph of a bee on a flower",
  "A whimsical treehouse built inside a giant, glowing mushroom",
  "An astronaut playing a guitar on the moon, with Earth in the background",
  "A steampunk airship soaring through a cloudy sky",
  "A knight in ornate, shining armor facing a massive dragon",
  "A tranquil Japanese zen garden with a cherry blossom tree, digital art",
  "A futuristic high-speed train traveling through a mountain pass",
  "A beautiful vampire queen on a gothic throne, oil painting style",
  "A post-apocalyptic survivor looking over a ruined city overgrown with nature",
  "A magical library where books fly off the shelves",
  "An intricate mechanical heart made of gears and glowing tubes, 3D render",
  "A vast desert landscape at sunset with two suns in the sky",
  "A low-poly art style render of a mountain range",
  "A watercolor painting of a quaint European village street",
  "A ghost ship sailing on a sea of clouds",
  "A minimalist vector logo for a company called 'Quantum Leap'",
  "A tiny, adorable dragon sleeping in a teacup",
  "The interior of a futuristic spaceship bridge",
  "A secret agent in a high-speed car chase, motion blur effect",
  "A double exposure portrait of a wolf and a snowy forest",
  "A glowing, magical sword stuck in a stone",
  "A food photography shot of a delicious, steaming bowl of ramen",
  "An old, mysterious map spread out on a wooden table",
  "A character from a Studio Ghibli film, in that distinct art style",
  "A city skyline reflected in a puddle after a storm",
  "A crystal cave with shimmering, luminous formations",
  "An abstract painting representing the feeling of 'joy'",
  "A close-up of a dragon's eye, highly detailed and reptilian",
  "A Victorian-era detective's office, complete with a magnifying glass and pipe",
  "A giant, ancient robot rusting in a field of flowers",
  "A tropical beach with crystal clear water and a hammock between two palm trees",
  "A beautiful geisha in a traditional kimono, ukiyo-e style",
  "A noir-style black and white photo of a mysterious woman in a fedora",
  "A powerful sorceress casting a complex spell, energy swirling around her",
  "A group of animals having a tea party in the woods",
  "A high-fashion model wearing a dress made of liquid chrome",
  "A bustling medieval marketplace full of interesting characters",
  "An alien world with strange, towering flora and purple skies",
  "A detailed architectural rendering of a modern, eco-friendly house",
  "A phoenix rising from the ashes, fiery and majestic",
  "A pirate ship battling a giant kraken during a storm",
  "A serene landscape painting in the style of Bob Ross",
  "A classic 1950s diner with a jukebox and neon signs",
  "A polar bear family under the aurora borealis",
  "A collection of magical potions on a dusty shelf",
  "A city built on the back of a colossal turtle",
  "An impossibly intricate mandala design, psychedelic colors",
  "A cute corgi dressed as a superhero",
  "A still life painting of fruit in a bowl, in the style of Cézanne",
  "A majestic eagle soaring over the Grand Canyon",
  "A futuristic soldier in powered armor, concept art",
  "A cozy hobbit-hole with a round door, nestled in a hillside",
  "The lost city of Atlantis, deep underwater",
  "An Art Deco style poster for a jazz club",
  "A glass apple with a galaxy swirling inside it",
  "A child looking at their reflection, which is an older version of themselves",
  "A samurai warrior meditating under a cherry blossom tree",
  "A sprawling sci-fi megastructure in deep space",
  "A whimsical illustration of a cat reading a book with glasses on",
  "A dramatic landscape photo of the Scottish Highlands",
  "A fantasy world map, with dragons and sea monsters",
  "A beautiful elven city built among giant trees",
  "A 3D render of a futuristic motorcycle",
  "A gritty, realistic portrait of a firefighter",
  "An impressionist painting of a lily pond, in the style of Monet",
  "A surreal image of a grand piano playing itself in a forest",
  "A close-up of a complex clockwork mechanism",
  "A delicious-looking stack of pancakes with syrup, food photography",
  "A warrior princess with a spear and shield, ready for battle",
  "A space station orbiting an alien planet",
  "A vintage robot from the 1950s",
  "A mythical griffin perched on a cliff",
  "A dark, moody forest with shafts of light breaking through the canopy",
  "An isometric view of a bustling city block",
  "A cubist-style portrait, in the style of Picasso",
  "A hacker surrounded by holographic screens",
  "A beautiful mermaid with iridescent scales",
  "A knight's helmet on a table, reflecting a past battle",
  "A solar eclipse over an ancient stone circle",
  "An intricate stained glass window depicting a mythological scene",
  "A Venetian masquerade ball with elaborate masks",
  "A cinematic shot of a lone wanderer in a vast, snowy landscape",
  "A cute, fluffy alien creature",
  "A bookshelf that opens into a secret passage",
  "A hyper-realistic drawing of a human eye",
  "A dreamlike scene with clouds made of cotton candy",
  "A bonsai tree growing on a floating rock",
  "A powerful wizard's staff, glowing with magical energy",
  "A synthwave-style sunset with a retro sports car",
  "A detailed illustration of the human circulatory system, stylized",
  "A world where the ground is a giant trampoline",
  "A majestic white stag with glowing antlers in an enchanted forest",
  "A quiet, rainy night in Tokyo, with glowing signs reflected on the wet pavement"
];

export default GENERATE_EXAMPLES;
