const GENERATE_EXAMPLES: string[] = [
  "Photorealistic portrait of a wise old wizard, intricate long white beard, detailed wrinkles, cinematic lighting",
  "A majestic lion wearing an ornate, jewel-encrusted crown, dramatic lighting, oil painting style",
  "A surreal underwater city with glowing jellyfish towers and bioluminescent coral reefs, digital art",
  "A retro-futuristic travel poster for a vacation on Mars, 'Visit the Red Planet!' text",
  "A friendly robot gardener with watering can hands, tending to exotic, glowing alien plants, detailed illustration",
  "A cozy, cluttered artist's studio attic, bathed in warm morning light streaming through a round window",
  "Epic fantasy landscape with floating islands connected by vine bridges, waterfalls cascading into the clouds",
  "A rainy cyberpunk city street at night, drenched in neon light from holographic signs, reflections on the wet pavement",
  "A highly detailed macro photograph of a dewdrop on a spider's web, revealing refracted colors",
  "A whimsical treehouse built inside a giant, glowing mushroom in an enchanted forest",
  "An astronaut playing an electric guitar on the moon, with the Earth rising in the star-filled background",
  "A magnificent steampunk airship with brass pipes and spinning propellers, soaring through a dramatic cloudy sky",
  "A brave knight in ornate, shining silver armor facing a colossal, fire-breathing dragon in a rocky canyon",
  "A tranquil Japanese zen garden with a cherry blossom tree and a koi pond, serene, digital art",
  "A futuristic, maglev high-speed train blurring through a breathtaking mountain pass at sunset",
  "A beautiful vampire queen on a gothic throne made of bones, in a dark castle, classical oil painting style",
  "A post-apocalyptic survivor with a dog, looking over a ruined city being reclaimed by nature",
  "A magical library where books fly like birds between towering, endless shelves",
  "An intricate, mechanical heart made of glowing gears, cogs, and tubes, detailed 3D render",
  "A vast, alien desert landscape at sunset with two suns and purple sand",
  "A low-poly art style render of a geometric mountain range at dawn",
  "A vibrant watercolor painting of a quaint, colorful European village street",
  "A ghostly pirate ship with tattered, glowing sails, sailing on a sea of clouds",
  "A minimalist vector logo for a tech company called 'Quantum Leap', using negative space",
  "A tiny, adorable, fluffy dragon sleeping soundly in a porcelain teacup",
  "The interior of a sleek, minimalist futuristic spaceship bridge, command viewscreen showing a nebula",
  "A secret agent in a high-speed car chase through Monaco, cinematic shot with motion blur",
  "A double exposure portrait of a woman's silhouette and a dense, misty forest",
  "A glowing, magical sword of legend stuck in an ancient, moss-covered stone",
  "A professional food photography shot of a delicious, steaming bowl of authentic Japanese ramen",
  "An old, mysterious, hand-drawn map with a sea monster, spread out on a captain's wooden table",
  "A charming character in the art style of Studio Ghibli, having a picnic in a field of flowers",
  "A sprawling city skyline perfectly reflected in a puddle after a thunderstorm",
  "A magical crystal cave with shimmering, luminous, rainbow-colored formations",
  "An abstract, dynamic painting representing the feeling of 'joy', using bold, bright colors",
  "An extreme close-up of a dragon's eye, highly detailed with reptilian scales and a fiery iris",
  "A Victorian-era detective's office, cluttered with books, maps, a magnifying glass, and a smoking pipe",
  "A giant, ancient robot from a lost civilization, covered in rust and vines in a field of flowers",
  "A tropical beach paradise with crystal clear turquoise water and a hammock between two palm trees",
  "A beautiful geisha in a traditional, intricate kimono, in the style of Japanese ukiyo-e woodblock prints",
  "A film noir style black and white photo of a mysterious woman in a fedora, half in shadow",
  "A powerful sorceress casting a complex spell, with raw magical energy swirling around her hands",
  "A group of woodland animals (a fox, a badger, a rabbit) having a formal tea party",
  "A high-fashion model on a runway, wearing a breathtaking dress made of flowing liquid chrome",
  "A bustling medieval marketplace, full of vendors, customers, and interesting characters",
  "A strange alien world with towering, bizarre flora and two purple moons in the sky",
  "A detailed architectural rendering of a modern, eco-friendly house integrated with nature",
  "A majestic phoenix rising from a pyre of ashes, with spectacular, fiery wings",
  "A massive pirate ship with black sails battling a giant kraken during a dramatic ocean storm",
  "A serene and happy little landscape painting in the joyful style of Bob Ross",
  "A classic 1950s American diner at night, with a glowing jukebox and neon signs",
  "A polar bear family, a mother and her cubs, under the vibrant green aurora borealis",
  "A collection of colorful, glowing magical potions in ornate glass bottles on a dusty shelf",
  "A fantasy city built on the back of a colossal, world-carrying turtle swimming through space",
  "An impossibly intricate, psychedelic-colored mandala design, symmetrical and detailed",
  "A cute, fluffy corgi wearing a tiny superhero cape, standing heroically on a rock",
  "A still life painting of a bowl of fruit, in the post-impressionist style of Cézanne",
  "A majestic bald eagle soaring over the Grand Canyon at sunrise, cinematic shot",
  "A futuristic soldier in sleek, powered armor, detailed concept art for a video game",
  "A cozy hobbit-hole with a round, green door, nestled in a lush, grassy hillside",
  "The majestic, lost city of Atlantis, illuminated by bioluminescent crystals deep underwater",
  "A stylish Art Deco poster for a glamorous 1920s jazz club",
  "A crystal clear glass apple with a swirling, miniature galaxy trapped inside it",
  "A child looking at their reflection in a puddle, but the reflection is an older, wiser version of themselves",
  "A lone samurai warrior meditating under a falling shower of cherry blossom petals",
  "A sprawling, awe-inspiring sci-fi megastructure, a Dyson sphere, in deep space",
  "A whimsical, detailed illustration of a cat wearing glasses, curled up reading a book by a fireplace",
  "A dramatic, moody landscape photograph of the rugged, misty Scottish Highlands",
  "A detailed, hand-drawn fantasy world map in the style of Tolkien, with dragons and sea monsters",
  "A beautiful, ethereal elven city built seamlessly among the branches of giant, ancient trees",
  "A clean, studio-shot 3D render of a futuristic, gloss white motorcycle",
  "A gritty, hyper-realistic, and emotional portrait of a veteran firefighter",
  "An impressionist painting of a lily pond, with soft light and colors, in the style of Monet",
  "A surreal image of a grand piano playing itself in the middle of an ancient, redwood forest",
  "An extreme close-up of a complex, antique clockwork mechanism in motion",
  "A delicious-looking stack of fluffy pancakes, dripping with maple syrup and topped with berries, food photography",
  "A fierce warrior princess with a spear and shield, adorned with tribal paint, ready for battle",
  "A massive space station orbiting a ringed, alien planet, sci-fi concept art",
  "A charming, vintage robot from the 1950s, holding a bouquet of flowers",
  "A mythical griffin with the body of a lion and the head of an eagle, perched on a cliff edge",
  "A dark, moody forest with shafts of golden light breaking through the dense canopy",
  "An isometric, detailed illustration of a single, bustling city block with tiny cars and people",
  "A cubist-style portrait of a person playing a cello, in the style of Picasso",
  "A young hacker in a hoodie, surrounded by glowing, holographic computer screens",
  "A beautiful, ethereal mermaid with iridescent scales and flowing hair, in a coral reef",
  "An ancient knight's helmet on a wooden table, reflecting a past battle in its visor",
  "A total solar eclipse viewed from behind a mystical, ancient stone circle",
  "An intricate, colorful stained glass window depicting a mythological scene",
  "A lavish Venetian masquerade ball with attendees in elaborate, mysterious masks and costumes",
  "A cinematic shot of a lone wanderer in a vast, snowy landscape during a blizzard",
  "A cute, fluffy, big-eyed alien creature, looking curious and friendly",
  "A secret passage revealed behind a bookshelf in a dusty, old library",
  "A hyper-realistic, detailed drawing of a human eye with a universe reflected in it",
  "A dreamlike, surreal scene with fluffy clouds made of pink cotton candy",
  "A beautiful bonsai tree growing on a small, levitating rock, against a serene background",
  "A powerful wizard's staff made of twisted wood, with a glowing crystal on top, pulsing with energy",
  "A synthwave-style sunset with a grid-patterned road and a retro sports car driving into the distance",
  "A stylized, detailed illustration of the human circulatory system, like an infographic",
  "A whimsical world where the ground is a giant, bouncy trampoline",
  "A majestic white stag with glowing, ethereal antlers, standing in an enchanted forest at night",
  "A quiet, rainy night in a Tokyo alley, with glowing ramen shop signs reflected on the wet pavement"
];

export default GENERATE_EXAMPLES;
