const NEGATIVE_PROMPT_EXAMPLES: string[] = [
  "Blurry",
  "Grainy",
  "Ugly",
  "Deformed",
  "Text",
  "Watermark",
  "Poorly drawn",
  "Extra limbs",
  "Missing fingers",
  "Deformed hands",
  "Malformed face",
  "Fused fingers",
  "Too many fingers",
  "Signature",
  "Username",
  "Logo",
  "Pixelated",
  "Low resolution",
  "Noisy",
  "JPEG artifacts",
  "Out of focus",
  "Overexposed",
  "Underexposed",
  "Bad anatomy",
  "Asymmetrical eyes",
  "Disfigured",
  "Morbid",
  "Mutilated",
  "Cluttered",
  "Flat lighting",
  "Boring",
  "Bad composition",
  "Cropped",
  "Out of frame",
  "Tiling",
  "Repetitive",
  "Unrealistic",
  "Cartoonish",
  "Amateur",
  "Bad art",
  "Floating limbs",
  "Disconnected body parts",
  "Unnatural colors",
  "Saturated",
  "Monochrome",
  "Grayscale",
  "Frame",
  "Border",
  "Caption",
  "Label",
  "Dirty",
  "Messy",
  "Undeveloped",
  "Poorly detailed",
  "Awkward pose",
  "Unnatural pose",
  "Stiff",
  "Lifeless",
  "Duplicate",
  "Multiple heads",
  "Multiple people",
  "Crowd",
  "Plastic look",
  "Waxy skin",
  "Error",
  "Glitched",
  "Scrambled",
  "Draft",
  "Sketch",
  "Unfinished",
  "Weird",
  "Strange",
  "Distorted",
  "Warped",
  "Twisted",
  "Contorted",
  "Broken limbs",
  "Double image",
  "Mirrored",
  "Flipped",
  "Generic",
  "Unimaginative",
  "Simple background",
  "White background",
  "Empty",
  "Vague",
  "Abstract",
  "Chaotic",
  "Malformed eyes",
  "Cross-eyed",
  "Lazy eye",
  "Body out of frame",
  "Head out of frame",
  "Cut off",
  "Missing arms",
  "Missing legs",
  "Extra arms",
  "Extra legs",
  "Long neck",
  "Elongated body",
  "Short body",
  "Poorly drawn feet",
  "Malformed feet",
  "Bad proportions",
  "Unbalanced",
  "Confusing",
  "Hazy",
  "Dark",
  "Gloomy",
  "Shadowy face",
  "CGI",
  "VFX",
  "3D render",
  "Video game",
  "Childish",
  "Poorly rendered",
  "Low quality"
];

export default NEGATIVE_PROMPT_EXAMPLES;
