const TIME_TRAVEL_EXAMPLES: string[] = [
  "A 1920s jazz singer on a smoky stage",
  "An astronaut exploring a new planet",
  "A Roman emperor addressing the Senate",
  "A knight in shining armor jousting",
  "A Viking warrior on a longship",
  "An ancient Egyptian pharaoh in their tomb",
  "A Victorian detective in a foggy London alley",
  "A samurai warrior in feudal Japan",
  "A Wild West cowboy in a desert standoff",
  "A flapper dancing at a Great Gatsby party",
  "A cyberpunk hacker in a neon-lit city",
  "A Renaissance artist painting a masterpiece",
  "A Greek philosopher debating in the agora",
  "A pilot of a futuristic starship on the bridge",
  "A medieval alchemist in a cluttered laboratory",
  "A resident of a utopian city on Mars",
  "An elf archer in a mythical forest",
  "A dragon rider soaring through the clouds",
  "A wizard casting a spell in a castle library",
  "A pirate captain on the deck of their ship",
  "A Cold War spy at a clandestine meeting",
  "A World War II pilot in a dogfight",
  "A Silk Road merchant with their caravan",
  "A Neanderthal hunting a woolly mammoth",
  "A Mayan priest at the top of a pyramid",
  "A steampunk inventor with their creation",
  "A god on Mount Olympus",
  "A 1950s greaser with a hot rod",
  "A hippie at the Woodstock festival",
  "A queen in her opulent royal court",
  "A gladiator fighting in the Colosseum",
  "A post-apocalyptic survivor in a ruined city",
  "A 1980s rock star with big hair",
  "A Colonial American minuteman",
  "An Aztec warrior in Tenochtitlan",
  "A monk in a tranquil Himalayan monastery",
  "A 1960s secret agent with cool gadgets",
  "A citizen of an underwater city",
  "A French musketeer in 17th-century Paris",
  "A roaring twenties gangster during Prohibition",
  "A Druid performing a ritual at Stonehenge",
  "A bio-engineered human in a lush alien jungle",
  "A Spartan warrior in the Battle of Thermopylae",
  "A field scientist studying dinosaurs",
  "A 1990s grunge musician in a garage band",
  "A knight of the Round Table in Camelot",
  "An android servant in a futuristic home",
  "A saloon singer in a dusty Western town",
  "A medieval scribe in a scriptorium",
  "A Celtic chieftain leading their clan",
  "A plague doctor in medieval Europe",
  "A Russian cosmonaut on the Mir space station",
  "A Polynesian navigator exploring the Pacific",
  "A Golden Age of Hollywood movie star",
  "A circus performer from the early 20th century",
  "A Ming dynasty imperial guard",
  "A Roaring Twenties pilot in an air race",
  "A Native American shaman",
  "A member of a futuristic law enforcement agency",
  "A traveling bard in a fantasy tavern",
  "An Incan emperor in Machu Picchu",
  "A '70s disco dancer under a disco ball",
  "A revolutionary during the French Revolution",
  "A beatnik poet in a Greenwich Village cafe",
  "A field nurse during the Crimean War",
  "A sorceress in her enchanted tower",
  "A member of an arctic exploration team in 1910",
  "A scholar in the Library of Alexandria",
  "A noir private eye in a dimly lit office",
  "A warrior from a nomadic steppe tribe",
  "A citizen of a floating sky-city",
  "A character in a Jules Verne novel",
  "A trader on the Venetian canals",
  "An early 20th-century Antarctic explorer",
  "A Roswell alien being examined",
  "A desert nomad in a sandstorm",
  "A character inside a virtual reality world",
  "A '40s swing dancer at the Savoy Ballroom",
  "A deep-sea diver discovering Atlantis",
  "A T-Rex herder on a prehistoric ranch",
  "A member of the Lewis and Clark expedition",
  "A fairy dwelling in a magical glen",
  "An old-timey radio show host",
  "A time-traveling historian, observing",
  "A Viking shieldmaiden",
  "A gondolier in Renaissance Venice",
  "A prospector during the California Gold Rush",
  "A character from a Shakespearean play",
  "A lighthouse keeper on a stormy night",
  "A dwarf blacksmith in a mountain forge",
  "A royal taster in a medieval castle",
  "A pilot in the Wright brothers' first flyer",
  "A secret agent from the swinging '60s",
  "An Oracle at Delphi, giving a prophecy",
  "A mob boss in 1930s Chicago",
  "A space colonist terraforming a planet",
  "A musketeer in the court of Louis XIII",
  "A kung fu master in ancient China",
  "A Roman charioteer in the Circus Maximus",
  "A soldier in the trenches of World War I"
];

export default TIME_TRAVEL_EXAMPLES;
