const TIME_TRAVEL_EXAMPLES: string[] = [
  "A 1920s jazz singer on a smoky stage, wearing a sequined dress and holding a vintage microphone",
  "An astronaut in a sleek, modern suit exploring a Mars-like planet with red sand and two moons in the sky",
  "A Roman emperor in a toga and laurel wreath, addressing the Senate in a grand marble hall",
  "A knight in full, polished plate armor during a jousting tournament, lance ready",
  "A fierce Viking warrior on the prow of a longship, sailing through a misty fjord",
  "An ancient Egyptian pharaoh in full regalia, standing inside a golden, hieroglyph-covered tomb",
  "A Victorian detective in a trench coat and deerstalker hat, investigating a foggy London alley at night",
  "A samurai warrior in traditional armor, meditating under a cherry blossom tree in feudal Japan",
  "A Wild West cowboy in a dusty standoff at high noon on a deserted street",
  "A flapper dancing energetically at a lavish Great Gatsby-style party with confetti falling",
  "A cyberpunk hacker with neon hair and cybernetics, in a cluttered room filled with holographic screens",
  "A Renaissance artist like Leonardo da Vinci, painting a masterpiece in a Florence studio",
  "A Greek philosopher in robes, debating with students in the sun-drenched agora of Athens",
  "The pilot of a futuristic starship on the bridge, with a nebula visible on the main viewscreen",
  "A medieval alchemist in a cluttered laboratory, surrounded by bubbling potions and ancient scrolls",
  "A resident of a utopian city on Mars, looking out from a biodome at the red landscape",
  "An elegant elf archer with pointed ears and intricate leather armor, in a mythical, sun-dappled forest",
  "A dragon rider soaring through the clouds on the back of a magnificent, scaled beast",
  "A powerful wizard in a tall, pointed hat, casting a spell in a vast castle library",
  "A grizzled pirate captain with a tricorn hat and a parrot on their shoulder, on the deck of a galleon",
  "A Cold War spy in a sharp suit, making a clandestine exchange on a bridge in Berlin",
  "A World War II fighter pilot in the cockpit of a Spitfire during a dogfight over the English Channel",
  "A wealthy Silk Road merchant leading a caravan of camels through a vast desert",
  "A Neanderthal hunter, clad in furs, tracking a woolly mammoth across a snowy tundra",
  "A Mayan high priest in a feathered headdress, performing a ceremony at the top of a stone pyramid",
  "A steampunk inventor in a workshop filled with brass contraptions and steam-powered devices",
  "A Greek god like Zeus, sitting on a throne of clouds on Mount Olympus",
  "A 1950s greaser with slicked-back hair, leaning against a classic hot rod outside a diner",
  "A hippie with flower-power attire and a guitar at the 1969 Woodstock festival",
  "An opulent queen like Marie Antoinette in her royal court at the Palace of Versailles",
  "A gladiator with a trident and net, fighting a tiger in the Roman Colosseum",
  "A post-apocalyptic survivor in rugged gear, scavenging in the ruins of a city overgrown with nature",
  "An 80s rock star with big hair and a studded leather jacket, on stage with a keytar",
  "A Colonial American minuteman, ready with his musket during the Revolutionary War",
  "An Aztec warrior in elaborate feathered armor, standing in the capital city of Tenochtitlan",
  "A Buddhist monk in saffron robes, meditating in a tranquil Himalayan monastery",
  "A suave 1960s secret agent with cool gadgets, in a high-stakes casino",
  "A citizen of a futuristic underwater city, with bioluminescent sea life swimming by the windows",
  "A French musketeer with a rapier and plumed hat, in 17th-century Paris",
  "A notorious gangster during Prohibition, in a pinstripe suit at a speakeasy",
  "An ancient Druid in white robes, performing a ritual within the stones of Stonehenge at sunrise",
  "A bio-engineered human in a lush, vividly colored alien jungle with strange creatures",
  "A Spartan warrior in a bronze helmet and red cape, in the Battle of Thermopylae",
  "A field paleontologist carefully uncovering dinosaur bones in the badlands",
  "A 90s grunge musician in a flannel shirt, playing a Fender Jaguar in a dimly lit garage",
  "A Knight of the Round Table, pledging allegiance to King Arthur in Camelot's great hall",
  "A helpful android servant in a minimalist, futuristic home",
  "A charismatic saloon singer in a feathered dress, performing on a small stage in a dusty Western town",
  "A medieval scribe with ink-stained fingers, illuminating a manuscript in a monastery scriptorium",
  "A Celtic chieftain with blue war paint, leading their clan into battle",
  "A mysterious plague doctor with a beaked mask, walking through a medieval European town",
  "A Russian cosmonaut floating inside the Mir space station, with Earth visible from the porthole",
  "A Polynesian navigator in a traditional canoe, using the stars to cross the Pacific Ocean",
  "A glamorous movie star from the Golden Age of Hollywood, at a red carpet premiere",
  "A circus strongman from the early 20th century, with a handlebar mustache and leopard-print singlet",
  "An imperial guard in ornate armor, standing watch in the Forbidden City of Ming Dynasty China",
  "An adventurous pilot from the Roaring Twenties, standing by their biplane before an air race",
  "A Native American shaman performing a spiritual ceremony by a crackling fire",
  "A member of a futuristic law enforcement agency, like a Blade Runner, in a flying vehicle",
  "A traveling bard with a lute, telling tales in a packed fantasy tavern",
  "An Incan emperor in a golden headdress, looking out over the mountains from Machu Picchu",
  "A 70s disco dancer in a white suit, under a glittering disco ball on a crowded dance floor",
  "A revolutionary in 1789 Paris, standing on the barricades during the French Revolution",
  "A beatnik poet in a black turtleneck, snapping their fingers in a smoky Greenwich Village cafe",
  "A dedicated field nurse like Florence Nightingale, tending to soldiers during the Crimean War",
  "A powerful sorceress in her enchanted tower, looking into a crystal ball",
  "A member of a daring arctic exploration team in 1910, with dog sleds and heavy furs",
  "A scholar in the Great Library of Alexandria, surrounded by countless ancient scrolls",
  "A noir private eye in a dimly lit office, with light streaming through the window blinds",
  "A fierce warrior from a nomadic steppe tribe like the Mongols, on horseback",
  "A citizen of a magnificent floating sky-city, with transports flying between buildings",
  "A character in a Jules Verne novel, like Captain Nemo aboard the Nautilus",
  "A merchant in Renaissance Venice, trading goods on the bustling canals",
  "An early 20th-century Antarctic explorer like Shackleton, with their ship trapped in the ice",
  "A Roswell alien being examined in a secret underground government facility",
  "A desert nomad leading a camel through a spectacular sandstorm",
  "A character inside a vibrant, Tron-like virtual reality world",
  "A 40s swing dancer doing the Lindy Hop at the Savoy Ballroom in Harlem",
  "A deep-sea diver in a heavy brass helmet, discovering the sunken city of Atlantis",
  "A futuristic T-Rex herder on a prehistoric ranch, using drones to manage the dinosaurs",
  "A member of the Lewis and Clark expedition, mapping the uncharted American West",
  "A tiny fairy with shimmering wings, dwelling in a magical glen filled with glowing flowers",
  "An old-timey radio show host from the 1930s, speaking into a large, classic microphone",
  "A time-traveling historian in a protective suit, observing a historical event without interfering",
  "A formidable Viking shieldmaiden, ready for battle with axe and shield",
  "A gondolier in Renaissance Venice, singing as they navigate the canals",
  "A prospector during the California Gold Rush, panning for gold in a river",
  "A character from a Shakespearean play, like Hamlet, performing on the Globe Theatre stage",
  "A solitary lighthouse keeper on a stormy night, with massive waves crashing against the rocks",
  "A dwarven blacksmith with a braided beard, forging a sword in a fiery mountain forge",
  "A royal taster in a medieval castle, cautiously sampling food for the king",
  "A pilot in the Wright brothers' first flyer at Kitty Hawk",
  "A groovy secret agent from the swinging '60s, like Austin Powers",
  "The Oracle at Delphi, giving a cryptic prophecy in a subterranean chamber",
  "A mob boss like Al Capone in 1930s Chicago, surrounded by his henchmen",
  "A space colonist on a new planet, working to terraform the environment",
  "A musketeer in the court of Louis XIII, engaged in a sword duel",
  "A wise kung fu master in ancient China, training students in a mountain temple",
  "A Roman charioteer racing in the Circus Maximus, with thousands of spectators cheering",
  "A soldier in the muddy trenches of World War I, writing a letter home"
];

export default TIME_TRAVEL_EXAMPLES;
